remote_theme: chrisrhymes/bulma-clean-theme@v0.13.3

title: "رضا طهورایی"
description: "پزشک شاعر"

lang: fa
direction: rtl

paginate: 5
paginate_path: "/poems/page:num"


defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      author: "Reza Tahurayi"
      layout: post
      show_sidebar: false
      categories: development
      published: true
